<?php

namespace PortlandLabs\Mpl;

use PhpParser\Node;
use PhpParser\PrettyPrinter\Standard;

class Printer extends Standard
{

    protected function pMaybeMultiline(array $nodes, bool $trailingComma = false): string
    {
        $firstNode = $nodes[0] ?? null;
        if ($firstNode && $firstNode->key) {
            return $this->pCommaSeparatedMultiline($nodes, $trailingComma) . $this->nl;
        }

        return parent::pMaybeMultiline($nodes, $trailingComma); // TODO: Change the autogenerated stub
    }
}
